language: c

sudo: false

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

# We test against different Stackage snapshots.
matrix:
  include:
    - env: BUILD=stack STACK_YAML=stack.yaml
    - env: BUILD=stack STACK_YAML=stack-lts-7.0.yaml
    - env: BUILD=stack STACK_YAML=stack-lts-6.0.yaml

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-elisp/ppa'
    packages:
    - hlint
    - python
    - python-numpy
    - libgmp-dev
    - emacs-snapshot

before_install:
 - export PATH=$HOME/.local/bin:$PATH
 - ./.travis-setup.sh

install:
 - stack build alex happy
 - stack --no-terminal test --only-dependencies -j 3

script:
 - stack --no-terminal test -j 3
 - stack install

# Now for integration testing
 - futhark-test --nobuffer tests # Run integration test suite.
# Numpy is broken on Travis in a weird way I can't reproduce anywhere else.
# - futhark-test tests examples --compiler=futhark-py --exclude=no_python -c # Run integration test suite with Python code generator.

 # Check for style issues.
 - if [ "$STACK_YAML" = stack.yaml ]; then
     stack install hlint --fast && tools/style-check.sh src;
   fi

 # Check the automatic indentation feature of the futhark-mode.el Emacs
 # editing mode.
 - if [ "$STACK_YAML" = stack.yaml ]; then
     cd tools && ./futhark-mode.el-corpus-test.sh;
   fi

# EOF
